### create 1 user
POST http://localhost:5031/api/v1/users
Content-Type: application/json

{
    "username": "dinghowchi",
    "password": "dinghowchi",
    "email": "hkkhj@gmail.com",
    "firstName": "Sam",
    "lastName": "Mhettri",
    "avatar": "cam110",
    "address": "cristinharju",
    "city": "Mspoo",
    "postalCode": "723",
    "country": "Ming",
    "phoneNumber": "1235767678"
}

### create admin
POST  http://localhost:5031/api/v1/users/admin/
Content-Type: application/json

{
  "username": "Krishana",
  "password": "kriss111",
  "email": "kriss@gmail.com",
  "firstName": "Krishna",
  "lastName": "Dwarika",
  "avatar": "Narayan",
  "address": "Baikunth",
  "city": "Kailash",
  "postalCode": "01010",
  "country": "Sagar",
  "phoneNumber": "28373782"
}
### create admin
POST  http://localhost:5031/api/v1/users/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3Y2E4YTI4NC1iNDUxLTQzZTQtOGU2OS00ZjMyZDcyNjRjMjciLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImtyaXNzQGdtYWlsLmNvbSIsIm5iZiI6MTY5MzA4NjMzMiwiZXhwIjoxNjkzMDg2OTMyLCJpYXQiOjE2OTMwODYzMzIsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.VSVk28t3zkGFWw2FBVDp7M5ljcmLMCBnsDkmhkpvPlQ

{
  "username": "Radhe",
  "password": "radhe1234",
  "email": "radhe@gmail.com",
  "firstName": "Radha",
  "lastName": "Kanaiya",
  "avatar": "Bansi",
  "address": "Devnagar",
  "city": "Kailash",
  "postalCode": "01010",
  "country": "World",
  "phoneNumber": "23423"
}
### login user
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "ram@gmail.com",
    "password": "ram123"
}

### login admin
POST http://localhost:5031/api/v1/auth/login
Content-Type: application/json

{
    "email": "raja@email.com",
    "password": "raja123"
}

### get all users
GET http://localhost:5000/api/v1/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYW1AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJSYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImExZjk4ODlkLWNkMmMtNGFlMy1iZDM0LTMzYTFkNmExOGQ3ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3N1cm5hbWUiOiJSYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy91cmkiOiJyYW1yYW0iLCJleHAiOjE3MTc0Mjg3MjcsImlzcyI6ImJhY2t1cC1teS1wcml2YXRlLWlzc3Vlci1mcm9tLWV2ZXJ5dGhpbmctU2VjcmV0SXNzdWVyIn0.1ufTAQyv0N--mxEVKZOilTFSWLWUqpoghjq6J9Ha8Xg